### ISSUE TITLE
Create script to pull latest and historical Elo ratings from CFBD

### ISSUE THREAD

**Issue by drewbennison** [kylebennison/staturdays#96]
This script will allow the user to pull historical Elo ratings using CFBD API, and also save a copy of the latest results to our data folder, ideally automatically. This replaces all of our previous Elo rating code.

**Comment by drewbennison** [comment]
Thinking about this more, I am not sure if there is really a reason for this. Would we ever want just access to Elo ratings without grabbing game data? It is quicker to have it stored, but if we just access through the games endpoint we never have to worry about being out of date.

**Comment by drewbennison** [comment]
@kylebennison, thoughts on the above?

**Comment by kylebennison** [comment]
Yeah, agreed since it already comes with games, probably simplest to just keep them together as one. The speed of the request is the only benefit to splitting them up, but we may as well store games + elo as one RDS and refresh it periodically via the API. That would be an issue for statRdaysCFB repo though.
